apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres 
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres/postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - name: http
    port: 8000           
    targetPort: 8000
  selector:
    app: postgres          
  type: LoadBalancer   
